In [1]:
import numpy as np
A=np.array([[1],[2],[3]])
B=np.array([[4],[5],[6]])
print(A,B)

[[1]
 [2]
 [3]] [[4]
 [5]
 [6]]


In [2]:
cross_product=np.zeros((3,1))
print(cross_product)

[[0.]
 [0.]
 [0.]]


In [10]:
for i in range(A.shape[0]):
    if i==A.shape[0]-1:
        cross_product[i]=(A[i]*B[0])-(B[i]*A[0])
    else:
        cross_product[i]=(A[i]*B[i+1])-(B[i]*A[i+1])

In [11]:
print(cross_product)

[[-3.]
 [-3.]
 [ 6.]]
