In [1]:
import numpy as np

In [3]:
A=np.random.randn(10,4)
B=np.random.randn(10,4)
result=np.zeros((10,4))

In [4]:
# matrix element wise multiplication
for i in range(A.shape[0]):
    for j in range(A.shape[1]):
        result[i,j]=A[i,j]*B[i,j]
print(result)

[[ 0.07174374  0.18538047 -0.36075707 -1.11569345]
 [ 0.6923826   0.37619805  0.13578051 -0.77864485]
 [ 1.8488424  -0.83473727 -0.30908934  0.15405368]
 [-0.00454431  0.22361394  0.25660539 -0.89449248]
 [ 2.23302921 -0.60293552  0.15772187 -0.12883724]
 [-0.04845748 -0.23627471 -0.56174722  0.24575027]
 [-0.16657219  0.41566614 -0.73528818 -0.09166446]
 [-0.75961456  0.20732131 -0.59609478  0.10056775]
 [-2.10687605  0.87800107  0.07664549  0.50472091]
 [ 0.30308414  0.0074355   0.31351938 -0.03898661]]


In [6]:
# shortcut or vectorize implementation
print(A*B)

[[ 0.07174374  0.18538047 -0.36075707 -1.11569345]
 [ 0.6923826   0.37619805  0.13578051 -0.77864485]
 [ 1.8488424  -0.83473727 -0.30908934  0.15405368]
 [-0.00454431  0.22361394  0.25660539 -0.89449248]
 [ 2.23302921 -0.60293552  0.15772187 -0.12883724]
 [-0.04845748 -0.23627471 -0.56174722  0.24575027]
 [-0.16657219  0.41566614 -0.73528818 -0.09166446]
 [-0.75961456  0.20732131 -0.59609478  0.10056775]
 [-2.10687605  0.87800107  0.07664549  0.50472091]
 [ 0.30308414  0.0074355   0.31351938 -0.03898661]]
