In [7]:
import numpy as np
A=np.array([[12,3,13,6],[1,15,7,5],[4,11,4,8],[18,2,6,8]])
print(A)

[[12  3 13  6]
 [ 1 15  7  5]
 [ 4 11  4  8]
 [18  2  6  8]]


In [5]:
x=np.array([[1],[2],[3],[4]])
print(x)

[[1]
 [2]
 [3]
 [4]]


In [10]:
def transformation(a,x):
    result=np.zeros((a.shape[0],x.shape[1]))
    for i in range(x.shape[0]):
        for j in range(a.shape[0]):
            result[i]+=a[i,j]*x[j]
    return result

In [11]:
print(transformation(A,x))

[[81.]
 [72.]
 [70.]
 [72.]]
