In [1]:
import numpy as np

In [2]:
x=np.random.randn(3,6)
y=np.random.randn(6,4)

In [25]:
result=np.zeros((3,4))
for i in range(len(x)):
    for j in range(len(y[0])):
        for k in range(len(y)):
            result[i,j]+=x[i,k]*y[k,j]
print(result)

[[ 0.57785595  0.28132796  0.36390316 -0.30567643]
 [-1.61129482 -0.60355623  2.51239767  1.10662685]
 [-0.80701702 -1.36033439  5.0336642  -1.80058926]]


In [26]:
print(np.dot(x,y))

[[ 0.57785595  0.28132796  0.36390316 -0.30567643]
 [-1.61129482 -0.60355623  2.51239767  1.10662685]
 [-0.80701702 -1.36033439  5.0336642  -1.80058926]]


In [27]:
print(np.matmul(x,y))

[[ 0.57785595  0.28132796  0.36390316 -0.30567643]
 [-1.61129482 -0.60355623  2.51239767  1.10662685]
 [-0.80701702 -1.36033439  5.0336642  -1.80058926]]
