In [10]:
import numpy as np

In [11]:
mat_A=np.random.randn(3,4)
mat_B=np.random.randn(3,4)

In [12]:
# matrix subtraction
out=np.zeros((3,4))
for i in range(mat_A.shape[0]):
    for j in range(mat_A.shape[1]):
        out[i,j]=mat_A[i,j]-mat_B[i,j]
print(out)

[[ 4.10444352e-01 -3.99533848e-01  1.14841181e+00  1.75618537e+00]
 [ 2.23584719e-01 -2.71459010e-01  7.78985496e-01 -9.64372536e-02]
 [-9.11772843e-02 -5.79725901e-02  2.80614799e+00  1.47165428e-03]]


In [13]:
# shortcut or vectorize implementation
print(mat_A-mat_B)

[[ 4.10444352e-01 -3.99533848e-01  1.14841181e+00  1.75618537e+00]
 [ 2.23584719e-01 -2.71459010e-01  7.78985496e-01 -9.64372536e-02]
 [-9.11772843e-02 -5.79725901e-02  2.80614799e+00  1.47165428e-03]]
