In [1]:
import numpy as np

In [5]:
matrix_A=np.random.randn(5,5)
matrix_B=np.random.randn(5,5)

In [6]:
# matrix addition
output=np.zeros((5,5))
for i in range(matrix_A.shape[0]):
    for j in range(matrix_A.shape[1]):
        output[i,j]=matrix_A[i,j]+matrix_B[i,j]
print(output)

[[ 0.09025671  1.99667043 -0.42306301  0.67264145 -1.82154609]
 [ 0.64638163 -0.84406757  3.57617163  2.68144627  0.32804879]
 [-2.05736349  0.43190664 -1.91255465 -1.55198875  1.56651952]
 [ 2.89093024 -0.53631511 -2.48946521 -2.25104504  0.78254721]
 [ 1.36413545  1.31868933 -0.49672    -1.08682511  0.56024609]]


In [8]:
# shortcut or vectorize implementation
print(matrix_A+matrix_B)

[[ 0.09025671  1.99667043 -0.42306301  0.67264145 -1.82154609]
 [ 0.64638163 -0.84406757  3.57617163  2.68144627  0.32804879]
 [-2.05736349  0.43190664 -1.91255465 -1.55198875  1.56651952]
 [ 2.89093024 -0.53631511 -2.48946521 -2.25104504  0.78254721]
 [ 1.36413545  1.31868933 -0.49672    -1.08682511  0.56024609]]
