In [1]:
import numpy as np

In [8]:
matrix=np.random.randn(10,10)
filter_matrix=np.array([[1,1,1],
                       [0,0,0],
                       [-1,-1,-1]])
print(matrix)
print(filter_matrix)

[[-1.06767827 -0.51275752  0.56100037  0.22490759 -0.18291807 -0.4870872
  -0.0101673  -0.44120567  0.74956917  0.3912265 ]
 [-1.22956163  0.63996842  0.85153649 -0.43401372  0.3776856  -0.2510585
  -0.93774316 -0.80486369 -0.27113764 -1.11036233]
 [-0.02000818 -0.41435292 -0.45817754 -0.3579896  -0.1306363  -0.55137574
   2.12719251 -0.40680042  0.12043113  0.04067795]
 [ 0.49930105  0.29317469  1.61136055  1.92132152 -0.82028037  0.70012572
  -0.37428437 -1.21696821 -1.65660519  0.72998066]
 [-1.82162628 -1.03276268 -1.45036073  0.97278037  0.74851449  1.22075254
  -0.2927485   0.83486889 -0.4149674  -0.73128332]
 [ 0.88996961  0.90896277 -0.47948061 -0.8602242   2.0379613   1.12664882
   0.76221192 -0.4513129   0.45891175 -1.0680693 ]
 [-0.09670809 -0.2359322  -1.64867481  0.26269899 -0.64673083  0.41660394
   0.20795292  1.51688645 -1.00382984 -1.28887961]
 [ 1.22370912  0.20255671 -0.18167328 -0.520216   -0.55202565 -1.22424149
   0.22091623  1.03633423  2.29096765 -0.26755654]
 [

In [9]:
n=matrix.shape[0]
m=filter_matrix.shape[0]
size=n-m+1
print(size)

8


In [5]:
# optimal way
def optimize_operation(x,f,s):
    optimize_mat=np.zeros((s,s))
    for i in range(x.shape[1]-2):
        for j in range(x.shape[0]-2):
            optimize_mat[i,j]=np.sum(x[i:i+f.shape[1],j:j+f.shape[0]]*f)
    return optimize_mat

In [10]:
print(optimize_operation(matrix,filter_matrix,size))

[[-0.12689678  1.50367049  1.54979332  0.59490396 -2.12535305 -2.10747653
  -1.54262703  0.94528134]
 [-2.14189301 -2.76836558 -1.91719334 -2.10855349 -0.31667704 -1.10253849
   1.23411327 -0.04277093]
 [ 3.41221105  0.27982298 -1.21773757 -3.98204904 -0.23133805 -0.59385657
   1.71367023  0.06569049]
 [ 1.08438452  4.25659881  2.01414522 -0.50321905 -4.42126107 -2.3286747
  -4.01766854 -1.08312228]
 [-2.32343458  0.11156499  2.30364079  2.9094753   1.6986925  -0.37857038
  -0.59385653  0.46444117]
 [ 0.07485922  0.06859053  1.95217143  4.60086906  5.48217295  1.40453887
  -2.77840734 -4.12021579]
 [-4.77636574 -4.3057649  -5.54738743 -0.01475691  0.94857048  4.23351844
  -0.05648114 -0.78947382]
 [ 0.98679111 -1.69957179 -1.92204067 -4.5732736  -2.75886757 -3.23733347
   1.32999371  0.0096857 ]]


In [11]:
matrix2=optimize_operation(matrix,filter_matrix,size)

In [14]:
size2=matrix2.shape[0]-filter_matrix.shape[0]+1

In [15]:
print(optimize_operation(matrix2,filter_matrix,size2))

[[  0.45227057   8.5683314    5.45046889   1.16931804  -6.66393221
   -3.89032636]
 [-14.18258048 -12.56163739  -1.43208897   3.72538579  10.58250205
    7.51826937]
 [  2.38252527 -10.2446447  -12.34293323  -9.03684107   0.16221003
    1.69348989]
 [  5.25950737  -0.85410605 -14.94554834 -18.74073571 -14.87590879
   -1.93538125]
 [ 14.72128925  15.19259031  11.52538244  -0.93773459  -4.3993422
   -3.89554923]
 [  4.73044253  14.81651709  21.28939529  22.05705553   8.77451182
   -3.5964302 ]]


In [18]:
matrix3=optimize_operation(matrix2,filter_matrix,size2)

In [19]:
size3=matrix3.shape[0]-filter_matrix.shape[0]+1

In [20]:
print(optimize_operation(matrix3,filter_matrix,size3))

[[  34.67612353   46.81253734   21.173419     -2.20379937]
 [ -17.63615982   24.27204953   61.43799171   57.37818296]
 [ -61.64431467  -57.40465718  -27.40586993    2.05148486]
 [ -51.37650193  -92.70335801 -100.68315548  -62.78716291]]
