In [1]:
import numpy as np
mat_A=np.random.randn(12,4)
print(mat_A)

[[-1.48037205 -0.18264137 -0.90482868  0.76307674]
 [ 0.65499761 -0.11654231 -0.69501872 -0.86428746]
 [-1.92465547 -0.02851981  0.6152346  -0.58887022]
 [ 0.01375068 -0.52268882  0.38488957  0.16666448]
 [-2.21926575 -0.6602078  -0.56495034 -1.33962878]
 [-1.66876715  2.06984471 -0.82888752  1.06126999]
 [ 0.88293593 -0.00971423 -0.31448834 -0.4373544 ]
 [-0.6260257  -0.52806665 -0.06238083 -0.22372117]
 [ 0.46288044 -0.78665897  0.10482402  1.34182098]
 [-0.16860537  1.15439238 -0.65312089  1.00970724]
 [ 1.46821981  1.12364938  0.34506855 -0.47383069]
 [-0.20747821 -0.07458384  0.07960047 -0.49048332]]


In [4]:
mat_A_T=np.zeros((4,12))
for i in range(mat_A.shape[0]):
    for j in range(mat_A.shape[1]):
        mat_A_T[j,i]=mat_A[i,j]
print(mat_A_T)

[[-1.48037205  0.65499761 -1.92465547  0.01375068 -2.21926575 -1.66876715
   0.88293593 -0.6260257   0.46288044 -0.16860537  1.46821981 -0.20747821]
 [-0.18264137 -0.11654231 -0.02851981 -0.52268882 -0.6602078   2.06984471
  -0.00971423 -0.52806665 -0.78665897  1.15439238  1.12364938 -0.07458384]
 [-0.90482868 -0.69501872  0.6152346   0.38488957 -0.56495034 -0.82888752
  -0.31448834 -0.06238083  0.10482402 -0.65312089  0.34506855  0.07960047]
 [ 0.76307674 -0.86428746 -0.58887022  0.16666448 -1.33962878  1.06126999
  -0.4373544  -0.22372117  1.34182098  1.00970724 -0.47383069 -0.49048332]]


In [6]:
print(mat_A.T)

[[-1.48037205  0.65499761 -1.92465547  0.01375068 -2.21926575 -1.66876715
   0.88293593 -0.6260257   0.46288044 -0.16860537  1.46821981 -0.20747821]
 [-0.18264137 -0.11654231 -0.02851981 -0.52268882 -0.6602078   2.06984471
  -0.00971423 -0.52806665 -0.78665897  1.15439238  1.12364938 -0.07458384]
 [-0.90482868 -0.69501872  0.6152346   0.38488957 -0.56495034 -0.82888752
  -0.31448834 -0.06238083  0.10482402 -0.65312089  0.34506855  0.07960047]
 [ 0.76307674 -0.86428746 -0.58887022  0.16666448 -1.33962878  1.06126999
  -0.4373544  -0.22372117  1.34182098  1.00970724 -0.47383069 -0.49048332]]


In [11]:
(mat_A.T==mat_A_T).all()

True